// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESPbEY1pO4RLAyegbU-Ni6VXCzxp4pQU',
    appId: '1:932830993877:android:7675c9053f9f315604315c',
    messagingSenderId: '932830993877',
    projectId: 'festivalrumour',
    storageBucket: 'festivalrumour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8njqRuhAa_nOVvBvKDkjFGk8NBK5EJU0',
    appId: '1:932830993877:ios:76ed99cad720006704315c',
    messagingSenderId: '932830993877',
    projectId: 'festivalrumour',
    storageBucket: 'festivalrumour.firebasestorage.app',
    iosClientId: '932830993877-372tlrvjog6gvh3a672ib169bja1li1l.apps.googleusercontent.com',
    iosBundleId: 'com.festival-rumour',
  );

}